"""init_all_tables

Revision ID: a5080d0be2ee
Revises: 
Create Date: 2026-03-03 13:24:11.873933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers used by Alembic.
revision: str = 'a5080d0be2ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('role', sa.Enum('doctor', 'admin', 'staff', name='user_role_enum'), server_default='staff', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('mrn', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'unknown', name='gender_enum'), server_default='unknown', nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_patients_metadata_gin', 'patients', ['metadata'], unique=False, postgresql_using='gin', postgresql_ops={'metadata': 'jsonb_path_ops'})
    op.create_index(op.f('ix_patients_created_by'), 'patients', ['created_by'], unique=False)
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('document_type', sa.Enum('lab_report', 'discharge_summary', 'clinical_note', 'imaging', 'prescription', 'other', name='document_type_enum'), server_default='other', nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='document_status_enum'), server_default='pending', nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('ai_model', sa.String(length=128), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_metadata_gin', 'documents', ['metadata'], unique=False, postgresql_using='gin', postgresql_ops={'metadata': 'jsonb_path_ops'})
    op.create_index('idx_documents_patient_created', 'documents', ['patient_id', 'created_at'], unique=False)
    op.create_index('idx_documents_status_active', 'documents', ['status'], unique=False, postgresql_where="status IN ('pending', 'processing')")
    op.create_index('idx_documents_type', 'documents', ['document_type'], unique=False)
    op.create_table('extracted_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ai_model', sa.String(length=128), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_data_gin', 'extracted_events', ['event_data'], unique=False, postgresql_using='gin', postgresql_ops={'event_data': 'jsonb_path_ops'})
    op.create_index('idx_events_document', 'extracted_events', ['document_id'], unique=False)
    op.create_index('idx_events_patient_timeline', 'extracted_events', ['patient_id', 'event_date'], unique=False)
    op.create_index('idx_events_patient_type', 'extracted_events', ['patient_id', 'event_type'], unique=False)
    op.create_index('idx_events_unverified', 'extracted_events', ['is_verified', 'created_at'], unique=False, postgresql_where='is_verified = false')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_unverified', table_name='extracted_events', postgresql_where='is_verified = false')
    op.drop_index('idx_events_patient_type', table_name='extracted_events')
    op.drop_index('idx_events_patient_timeline', table_name='extracted_events')
    op.drop_index('idx_events_document', table_name='extracted_events')
    op.drop_index('idx_events_data_gin', table_name='extracted_events', postgresql_using='gin', postgresql_ops={'event_data': 'jsonb_path_ops'})
    op.drop_table('extracted_events')
    op.drop_index('idx_documents_type', table_name='documents')
    op.drop_index('idx_documents_status_active', table_name='documents', postgresql_where="status IN ('pending', 'processing')")
    op.drop_index('idx_documents_patient_created', table_name='documents')
    op.drop_index('idx_documents_metadata_gin', table_name='documents', postgresql_using='gin', postgresql_ops={'metadata': 'jsonb_path_ops'})
    op.drop_table('documents')
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.drop_index(op.f('ix_patients_created_by'), table_name='patients')
    op.drop_index('idx_patients_metadata_gin', table_name='patients', postgresql_using='gin', postgresql_ops={'metadata': 'jsonb_path_ops'})
    op.drop_table('patients')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
